### ISSUE TITLE
"config" is not working

### ISSUE THREAD

**Issue by menegazzo** [jacobscarter/angular-cron-jobs#36]
I'm trying to perform a basic configuration by removing select options *Minute* and *Hour* following the instruction given on [Demo with config](http://jacobscarter.github.io/angular-cron-jobs/). Even at the demo page the component is not behaving as expected (both month and year are still there).

At first view `$scope.config` is `undefined` when app reaches the code where the options should be removed.

**Comment by jacobscarter** [comment]
Hi @menegazzo the demo wasn't working because it was running version 1.3.3 of angular-cron-jobs.  I updated it to the new version and it works fine.

Can you create a fiddle of your un-working code and I can try and debug it for you? But also I would first check that you are running version 1.4.1 or higher.

**Comment by menegazzo** [comment]
@jacobscarter I figured out my mistake: I'm using Angular Material and the `cron-selection` directive is used inside a dialog. It is necessary to share the same `$scope` to make it work properly. :sweat_smile:

Sorry about this and thank you for the good work! :metal:

**Comment by jacobscarter** [comment]
Glad you got it figure out :)
